package application;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import application.DFA_Sampling.State1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author merve
 */
public class DFA_Sampling extends javax.swing.JFrame {

    public static enum State1 {
        a, b, c, d
    } //enumerated class

    Map<String, JButton> butonMap0 = new HashMap<>();
    Map<String, JButton> butonMap1 = new HashMap<>();
    Map<Integer, JPanel> panelMap = new HashMap<>();
    Map<Integer, JLabel> labelMap = new HashMap<>();
    Map<Integer, JLabel> symbolMap = new HashMap<>();
    static int nextCounter = 1;
    State1 s;
    int deltaNo = 1;
    boolean result = false;
    boolean finish = false;

    /**
     * Creates new form DFA
     */
    public DFA_Sampling() {
        initComponents();
        Arrowa.setVisible(false);
       
        f1.setVisible(false);
        f2.setVisible(false);
        f3.setVisible(false);
        f4.setVisible(false);
        f5.setVisible(false);
        f6.setVisible(false);
        f7.setVisible(false);
        f8.setVisible(false);
        f9.setVisible(false);
        f10.setVisible(false);
        f11.setVisible(false);

        symbol1.setVisible(false);
        symbol2.setVisible(false);
        symbol3.setVisible(false);
        symbol4.setVisible(false);
        symbol5.setVisible(false);
        symbol6.setVisible(false);
        symbol7.setVisible(false);
        symbol8.setVisible(false);
        symbol9.setVisible(false);
        symbol9.setVisible(false);
        symbol10.setVisible(false);
        nextStat.setVisible(false);

        butonMap0.put(stat1.getText(), newState1);
        butonMap0.put(stat2.getText(), newState3);
        butonMap0.put(stat3.getText(), newState5);
        butonMap0.put(stat4.getText(), newState7);

        butonMap1.put(stat1.getText(), newState2);
        butonMap1.put(stat2.getText(), newState4);
        butonMap1.put(stat3.getText(), newState6);
        butonMap1.put(stat4.getText(), newState8);

        panelMap.put(1, f1);
        panelMap.put(2, f2);
        panelMap.put(3, f3);
        panelMap.put(4, f4);
        panelMap.put(5, f5);
        panelMap.put(6, f6);
        panelMap.put(7, f7);
        panelMap.put(8, f8);
        panelMap.put(9, f9);
        panelMap.put(10, f10);
        panelMap.put(11, f11);        

        labelMap.put(1, field1);
        labelMap.put(2, field2);
        labelMap.put(3, field3);
        labelMap.put(4, field4);
        labelMap.put(5, field5);
        labelMap.put(6, field6);
        labelMap.put(7, field7);
        labelMap.put(8, field8);
        labelMap.put(9, field9);
        labelMap.put(10, field10);
        labelMap.put(11, field11);

        symbolMap.put(1, symbol1);
        symbolMap.put(2, symbol2);
        symbolMap.put(3, symbol3);
        symbolMap.put(4, symbol4);
        symbolMap.put(5, symbol5);
        symbolMap.put(6, symbol6);
        symbolMap.put(7, symbol7);
        symbolMap.put(8, symbol8);
        symbolMap.put(9, symbol9);
        symbolMap.put(10, symbol10);
        
        DFA1();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        grammerText = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        inputText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grammerList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        ChooseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        transitionMatrix = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        input0 = new javax.swing.JButton();
        input1 = new javax.swing.JButton();
        stat1 = new javax.swing.JButton();
        stat2 = new javax.swing.JButton();
        stat3 = new javax.swing.JButton();
        newState1 = new javax.swing.JButton();
        newState2 = new javax.swing.JButton();
        newState4 = new javax.swing.JButton();
        newState3 = new javax.swing.JButton();
        newState5 = new javax.swing.JButton();
        newState6 = new javax.swing.JButton();
        stat4 = new javax.swing.JButton();
        newState7 = new javax.swing.JButton();
        newState8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Arrowd = new javax.swing.JLabel();
        Arrowa = new javax.swing.JLabel();
        symbol1 = new javax.swing.JLabel();
        f1 = new javax.swing.JPanel();
        field1 = new javax.swing.JLabel();
        nextButon = new javax.swing.JButton();
        nextStat = new javax.swing.JLabel();
        f2 = new javax.swing.JPanel();
        field2 = new javax.swing.JLabel();
        f3 = new javax.swing.JPanel();
        field3 = new javax.swing.JLabel();
        symbol2 = new javax.swing.JLabel();
        transitionDiagramPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        f4 = new javax.swing.JPanel();
        field4 = new javax.swing.JLabel();
        symbol3 = new javax.swing.JLabel();
        symbol4 = new javax.swing.JLabel();
        f5 = new javax.swing.JPanel();
        field5 = new javax.swing.JLabel();
        symbol5 = new javax.swing.JLabel();
        symbol6 = new javax.swing.JLabel();
        symbol7 = new javax.swing.JLabel();
        symbol8 = new javax.swing.JLabel();
        f6 = new javax.swing.JPanel();
        field6 = new javax.swing.JLabel();
        f7 = new javax.swing.JPanel();
        field7 = new javax.swing.JLabel();
        f8 = new javax.swing.JPanel();
        field8 = new javax.swing.JLabel();
        f9 = new javax.swing.JPanel();
        field9 = new javax.swing.JLabel();
        symbol9 = new javax.swing.JLabel();
        f10 = new javax.swing.JPanel();
        field10 = new javax.swing.JLabel();
        AcceptRejectLbl = new javax.swing.JLabel();
        symbol10 = new javax.swing.JLabel();
        f11 = new javax.swing.JPanel();
        field11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deterministic Finite Automata");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        grammerText.setEditable(false);
        grammerText.setText("{w | w has both an even number of 0's and an even number of 1's}");

        startButton.setText("Start DFA");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        inputText.setText("1001");
        inputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTextKeyReleased(evt);
            }
        });

        grammerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "{w | w has both an even number of 0's and an even number of 1's}", "{w | w starts with 100} ", "{w | w ends with 111 } ", "{w | w starts with 1 and ends with 10}", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(grammerList);

        jLabel3.setText("Choose one of these grammars:");

        ChooseButton.setText("Choose");
        ChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("        ");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(startButton)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(grammerText)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ChooseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(inputText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(0, 159, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(grammerText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ChooseButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(inputText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transitionMatrix.setBackground(new java.awt.Color(102, 255, 153));
        transitionMatrix.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Transition Matrix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(51, 51, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator1.setBackground(new java.awt.Color(51, 102, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        input0.setBackground(new java.awt.Color(153, 204, 255));
        input0.setText("0");
        input0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input0ActionPerformed(evt);
            }
        });

        input1.setBackground(new java.awt.Color(153, 204, 255));
        input1.setText("1");
        input1.setName(""); // NOI18N

        stat1.setBackground(new java.awt.Color(153, 204, 255));
        stat1.setText("a");

        stat2.setBackground(new java.awt.Color(153, 204, 255));
        stat2.setText("b");

        stat3.setBackground(new java.awt.Color(153, 204, 255));
        stat3.setText("c");

        newState1.setText("b");
        newState1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newState1ActionPerformed(evt);
            }
        });

        newState2.setText("c");

        newState4.setText("a");

        newState3.setText("d");

        newState5.setText("c");

        newState6.setText("a");

        stat4.setBackground(new java.awt.Color(153, 204, 255));
        stat4.setText("d");

        newState7.setText("b");

        newState8.setText("d");
        newState8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newState8ActionPerformed(evt);
            }
        });

        jLabel4.setText("Inputs->");

        jLabel5.setText("*");

        Arrowd.setText("→");

        Arrowa.setText("→");

        org.jdesktop.layout.GroupLayout transitionMatrixLayout = new org.jdesktop.layout.GroupLayout(transitionMatrix);
        transitionMatrix.setLayout(transitionMatrixLayout);
        transitionMatrixLayout.setHorizontalGroup(
            transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transitionMatrixLayout.createSequentialGroup()
                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(transitionMatrixLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(stat2)
                            .add(stat3)
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(Arrowd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(stat4))
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(Arrowa)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(stat1)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(input0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(newState7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(newState5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(newState3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(newState1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(23, 23, 23)
                                .add(input1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(newState4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(newState6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(transitionMatrixLayout.createSequentialGroup()
                                        .add(1, 1, 1)
                                        .add(newState2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(newState8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(transitionMatrixLayout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        transitionMatrixLayout.linkSize(new java.awt.Component[] {newState1, newState2, newState3, newState4, newState5, newState6, newState7, newState8}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        transitionMatrixLayout.linkSize(new java.awt.Component[] {stat1, stat2, stat3, stat4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        transitionMatrixLayout.setVerticalGroup(
            transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transitionMatrixLayout.createSequentialGroup()
                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(transitionMatrixLayout.createSequentialGroup()
                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(input0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(68, 68, 68)
                                .add(newState1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(newState7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(transitionMatrixLayout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(input1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(transitionMatrixLayout.createSequentialGroup()
                                        .add(7, 7, 7)
                                        .add(jLabel4)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(newState2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(transitionMatrixLayout.createSequentialGroup()
                                        .add(42, 42, 42)
                                        .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(newState4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(newState3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(newState6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(newState5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, 13, Short.MAX_VALUE)
                                .add(newState8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jSeparator3)
                            .add(transitionMatrixLayout.createSequentialGroup()
                                .add(61, 61, 61)
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(stat1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel5)
                                    .add(Arrowa))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(stat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(stat3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(transitionMatrixLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(stat4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Arrowd))))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transitionMatrixLayout.linkSize(new java.awt.Component[] {newState1, newState2, newState3, newState4, newState5, newState6, newState7, newState8}, org.jdesktop.layout.GroupLayout.VERTICAL);

        symbol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        f1.setBackground(new java.awt.Color(102, 255, 153));

        field1.setBackground(new java.awt.Color(255, 0, 0));
        field1.setText("(a, 1001)");

        org.jdesktop.layout.GroupLayout f1Layout = new org.jdesktop.layout.GroupLayout(f1);
        f1.setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(f1Layout.createSequentialGroup()
                .add(field1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f1Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        nextButon.setText("Next");
        nextButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButonActionPerformed(evt);
            }
        });

        nextStat.setText("δ (a, 1)");

        f2.setBackground(new java.awt.Color(102, 255, 153));

        field2.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f2Layout = new org.jdesktop.layout.GroupLayout(f2);
        f2.setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f2Layout.createSequentialGroup()
                .addContainerGap()
                .add(field2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f2Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        f3.setBackground(new java.awt.Color(102, 255, 153));

        field3.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f3Layout = new org.jdesktop.layout.GroupLayout(f3);
        f3.setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(f3Layout.createSequentialGroup()
                .addContainerGap()
                .add(field3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f3Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        symbol2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        transitionDiagramPanel.setBackground(new java.awt.Color(102, 255, 153));
        transitionDiagramPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Transition Diagram", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        org.jdesktop.layout.GroupLayout transitionDiagramPanelLayout = new org.jdesktop.layout.GroupLayout(transitionDiagramPanel);
        transitionDiagramPanel.setLayout(transitionDiagramPanelLayout);
        transitionDiagramPanelLayout.setHorizontalGroup(
            transitionDiagramPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, transitionDiagramPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        transitionDiagramPanelLayout.setVerticalGroup(
            transitionDiagramPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Choose a grammar that shown below, give your input and click the Start DFA, to see the next statement click the Next! ");

        f4.setBackground(new java.awt.Color(102, 255, 153));

        field4.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f4Layout = new org.jdesktop.layout.GroupLayout(f4);
        f4.setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f4Layout.createSequentialGroup()
                .addContainerGap()
                .add(field4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(field4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        symbol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        symbol4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        f5.setBackground(new java.awt.Color(102, 255, 153));

        field5.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f5Layout = new org.jdesktop.layout.GroupLayout(f5);
        f5.setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f5Layout.createSequentialGroup()
                .addContainerGap()
                .add(field5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f5Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        symbol5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        symbol6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        symbol7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        symbol8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        f6.setBackground(new java.awt.Color(102, 255, 153));

        field6.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f6Layout = new org.jdesktop.layout.GroupLayout(f6);
        f6.setLayout(f6Layout);
        f6Layout.setHorizontalGroup(
            f6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f6Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(field6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        f6Layout.setVerticalGroup(
            f6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f6Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        f7.setBackground(new java.awt.Color(102, 255, 153));

        field7.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f7Layout = new org.jdesktop.layout.GroupLayout(f7);
        f7.setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(f7Layout.createSequentialGroup()
                .addContainerGap()
                .add(field7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f7Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        f8.setBackground(new java.awt.Color(102, 255, 153));

        field8.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f8Layout = new org.jdesktop.layout.GroupLayout(f8);
        f8.setLayout(f8Layout);
        f8Layout.setHorizontalGroup(
            f8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f8Layout.createSequentialGroup()
                .addContainerGap()
                .add(field8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        f8Layout.setVerticalGroup(
            f8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f8Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        f9.setBackground(new java.awt.Color(102, 255, 153));

        field9.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f9Layout = new org.jdesktop.layout.GroupLayout(f9);
        f9.setLayout(f9Layout);
        f9Layout.setHorizontalGroup(
            f9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f9Layout.createSequentialGroup()
                .addContainerGap()
                .add(field9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        f9Layout.setVerticalGroup(
            f9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f9Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        symbol9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        f10.setBackground(new java.awt.Color(102, 255, 153));

        field10.setBackground(new java.awt.Color(0, 204, 204));

        org.jdesktop.layout.GroupLayout f10Layout = new org.jdesktop.layout.GroupLayout(f10);
        f10.setLayout(f10Layout);
        f10Layout.setHorizontalGroup(
            f10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f10Layout.createSequentialGroup()
                .addContainerGap()
                .add(field10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        f10Layout.setVerticalGroup(
            f10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, f10Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(field10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        AcceptRejectLbl.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        AcceptRejectLbl.setForeground(new java.awt.Color(255, 0, 0));
        AcceptRejectLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        symbol10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yieldSymbol.png"))); // NOI18N

        f11.setBackground(new java.awt.Color(102, 255, 153));

        org.jdesktop.layout.GroupLayout f11Layout = new org.jdesktop.layout.GroupLayout(f11);
        f11.setLayout(f11Layout);
        f11Layout.setHorizontalGroup(
            f11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(f11Layout.createSequentialGroup()
                .addContainerGap()
                .add(field11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        f11Layout.setVerticalGroup(
            f11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(field11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Made by Merve Özdemir");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 867, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(nextButon)
                                            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(transitionMatrix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(nextStat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                                .add(transitionDiagramPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(f1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(symbol1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(f2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(symbol2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(f3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(symbol3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(f4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(symbol4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(f5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(symbol5)
                                .add(18, 18, 18)
                                .add(f6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(symbol6)
                                .add(18, 18, 18)
                                .add(f7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(symbol7)
                                .add(18, 18, 18)
                                .add(f8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(symbol8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(f9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(symbol9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(f10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(symbol10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(f11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(AcceptRejectLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 403, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(127, 127, 127))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(transitionMatrix, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(transitionDiagramPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nextButon)
                    .add(nextStat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(symbol2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(f1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(f3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(f2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(symbol1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(symbol3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(symbol4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(f4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(f5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(symbol5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(symbol6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(f7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(symbol7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(f8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(f6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(f9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(f10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(symbol9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, f11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, symbol10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(symbol8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(AcceptRejectLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jLabel7)
                .add(9, 9, 9))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void DFA1() {
        Arrowd.setVisible(false);
        Arrowa.setVisible(true);

        butonMap0.get("a").setText("c");
        butonMap0.get("b").setText("d");
        butonMap0.get("c").setText("a");
        butonMap0.get("d").setText("b");

        butonMap1.get("a").setText("b");
        butonMap1.get("b").setText("a");
        butonMap1.get("c").setText("d");
        butonMap1.get("d").setText("c");

        try {
            jLabel1.setIcon(new ImageIcon(new ImageIcon(ImageIO.read(this.getClass().getResource("/images/grammer1.png"))).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT)));
        } catch (IOException ex) {
            Logger.getLogger(DFA_Sampling.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void DFA2() {
        Arrowd.setVisible(true);
        Arrowa.setVisible(false);
        butonMap0.get("a").setText("Ø");
        butonMap0.get("b").setText("c");
        butonMap0.get("c").setText("d");
        butonMap0.get("d").setText("d");

        butonMap1.get("a").setText("b");
        butonMap1.get("b").setText("Ø");
        butonMap1.get("c").setText("Ø");
        butonMap1.get("d").setText("d");

        try {
            jLabel1.setIcon(new ImageIcon(new ImageIcon(ImageIO.read(this.getClass().getResource("/images/grammer2.png"))).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT)));
        } catch (IOException ex) {
            Logger.getLogger(DFA_Sampling.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void DFA3() {
        Arrowd.setVisible(true);
        Arrowa.setVisible(false);
        butonMap0.get("a").setText("a");
        butonMap0.get("b").setText("a");
        butonMap0.get("c").setText("a");
        butonMap0.get("d").setText("a");

        butonMap1.get("a").setText("b");
        butonMap1.get("b").setText("c");
        butonMap1.get("c").setText("d");
        butonMap1.get("d").setText("d");

        try {
            jLabel1.setIcon(new ImageIcon(new ImageIcon(ImageIO.read(this.getClass().getResource("/images/grammer3.png"))).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT)));
        } catch (IOException ex) {
            Logger.getLogger(DFA_Sampling.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void DFA4() {
        Arrowd.setVisible(true);
        Arrowa.setVisible(false);

        butonMap0.get("a").setText("Ø");
        butonMap0.get("b").setText("b");
        butonMap0.get("c").setText("d");
        butonMap0.get("d").setText("b");

        butonMap1.get("a").setText("b");
        butonMap1.get("b").setText("c");
        butonMap1.get("c").setText("c");
        butonMap1.get("d").setText("c");
        try {
            jLabel1.setIcon(new ImageIcon(new ImageIcon(ImageIO.read(this.getClass().getResource("/images/grammer4.png"))).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT)));
        } catch (IOException ex) {
            Logger.getLogger(DFA_Sampling.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public State1 delta1(State1 q, char c) {
        if (q == State1.a && c == '1') {
            return State1.b;
        }
        if (q == State1.a && c == '0') {
            return State1.c;
        }
        if (q == State1.b && c == '0') {
            return State1.d;
        }
        if (q == State1.b && c == '1') {
            return State1.a;
        }
        if (q == State1.c && c == '0') {
            return State1.a;
        }
        if (q == State1.c && c == '1') {
            return State1.d;
        }
        if (q == State1.d && c == '1') {
            return State1.c;
        }
        if (q == State1.d && c == '0') {
            return State1.b;
        }
        return null;  //default is null -- no transition
    }

    public State1 delta2(State1 q, char c) {
        if (q == State1.a && c == '1') {
            return State1.b;
        }
        if (q == State1.b && c == '0') {
            return State1.c;
        }
        if (q == State1.c && c == '0') {
            return State1.d;
        }
        if (q == State1.d) {
            return State1.d;
        }
        return null;  //default is null -- no transition
    }

    public State1 delta3(State1 q, char c) {
        if (q == State1.a && c == '0') {
            return State1.a;
        }
        if (q == State1.a && c == '1') {
            return State1.b;
        }
        if (q == State1.b && c == '0') {
            return State1.a;
        }
        if (q == State1.b && c == '1') {
            return State1.c;
        }
        if (q == State1.c && c == '0') {
            return State1.a;
        }
        if (q == State1.c && c == '1') {
            return State1.d;
        }
        if (q == State1.d && c == '1') {
            return State1.d;
        }
        if (q == State1.d && c == '0') {
            return State1.a;
        }
        return null;  //default is null -- no transition
    }

    public State1 delta4(State1 q, char c) {
        if (q == State1.a && c == '1') {
            return State1.b;
        }
        if (q == State1.b && c == '0') {
            return State1.b;
        }
        if (q == State1.b && c == '1') {
            return State1.c;
        }
        if (q == State1.c && c == '0') {
            return State1.d;
        }
        if (q == State1.c && c == '1') {
            return State1.c;
        }
        if (q == State1.d && c == '1') {
            return State1.c;
        }
        if (q == State1.d && c == '0') {
            return State1.b;
        }

        return null;  //default is null -- no transition
    }

    void turnOffTheButtons() {
        for (Map.Entry<String, JButton> entry : butonMap0.entrySet()) {
            String key = entry.getKey();
            JButton value = entry.getValue();
            value.setBackground(Color.getColor("EEEEEE"));
        }
        for (Map.Entry<String, JButton> entry : butonMap1.entrySet()) {
            String key = entry.getKey();
            JButton value = entry.getValue();
            value.setBackground(Color.getColor("EEEEEE"));
        }
    }

    void lightTheButton(State1 q, char c) {
        turnOffTheButtons();

        if (c == '0') {
            // input0.setBackground(Color.green);
            if (butonMap0.containsKey(q.toString())) {
                butonMap0.get(q.toString()).setBackground(Color.red);
            }
        } else if (c == '1') {
            if (butonMap1.containsKey(q.toString())) {
                butonMap1.get(q.toString()).setBackground(Color.red);
            }
        } else {

        }
    }


    private void ChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseButtonActionPerformed
        grammerText.setText(grammerList.getSelectedValue());
        switch (grammerList.getSelectedIndex()) {
            case 0:
                deltaNo = 1;
                DFA1();
                break;
            case 1:
                deltaNo = 2;
                DFA2();
                break;
            case 2:
                deltaNo = 3;
                DFA3();
                break;
            case 3:
                deltaNo = 4;
                DFA4();
                break;
            default:
                break;
        }


    }//GEN-LAST:event_ChooseButtonActionPerformed

    private void newState1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newState1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newState1ActionPerformed

    private void input0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input0ActionPerformed

    private void newState8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newState8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newState8ActionPerformed


    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        AcceptRejectLbl.setText("");
        finish = false;
        s = State1.a;
        nextCounter = 1;
        field1.setText("(a, " + inputText.getText() + ")");
        nextStat.setText("Next Statement: δ (a, " + inputText.getText().charAt(0) + ")");
        lightTheButton(s, inputText.getText().charAt(0));

        f1.setVisible(true);
        symbol1.setVisible(true);
        nextStat.setVisible(true);

        f2.setVisible(false);
        f3.setVisible(false);
        f4.setVisible(false);
        f5.setVisible(false);
        f6.setVisible(false);
        f7.setVisible(false);
        f8.setVisible(false);
        f9.setVisible(false);
        f10.setVisible(false);
        f11.setVisible(false);

        symbol2.setVisible(false);
        symbol3.setVisible(false);
        symbol4.setVisible(false);
        symbol5.setVisible(false);
        symbol6.setVisible(false);
        symbol7.setVisible(false);
        symbol8.setVisible(false);
        symbol9.setVisible(false);
        symbol10.setVisible(false);


    }//GEN-LAST:event_startButtonActionPerformed
    boolean getResult(int deltaNo) {
        boolean result = false;

        switch (deltaNo) {
            case 1:
                Automaton dfa1 = new DFA1();
                result = dfa1.test(inputText.getText());
                break;
            case 2:
                Automaton dfa2 = new DFA2();
                result = dfa2.test(inputText.getText());
                break;
            case 3:
                Automaton dfa3 = new DFA3();
                result = dfa3.test(inputText.getText());
                break;
            case 4:
                Automaton dfa4 = new DFA4();
                result = dfa4.test(inputText.getText());
                break;
            default:
                break;
        }

        return result;
    }
    private void nextButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButonActionPerformed
        if (!finish) {
            char c = inputText.getText().charAt(nextCounter - 1);
            State1 t = null;
            if (deltaNo == 1) {
                t = delta1(s, c);
            } else if (deltaNo == 2) {
                t = delta2(s, c);
            } else if (deltaNo == 3) {
                t = delta3(s, c);
            } else if (deltaNo == 4) {
                t = delta4(s, c);
            }

            if (nextCounter == inputText.getText().length()) {
                turnOffTheButtons();
                if (inputText.getText().length() == 1) {
                    panelMap.get(nextCounter + 1).setVisible(true);
                    if (t == null) {
                        labelMap.get(nextCounter + 1).setText("(Ø, ε)");
                    } else {
                        labelMap.get(nextCounter + 1).setText("(" + t + ", ε)");
                        nextStat.setText("Next Statement : δ (" + t + ", ε)");
                    }
                    result = getResult(deltaNo);
                } else {
                    panelMap.get(nextCounter + 1).setVisible(true);
                    if (t == null) {
                        labelMap.get(nextCounter + 1).setText("(Ø, ε)");
                    } else {
                        labelMap.get(nextCounter + 1).setText("(" + t + ", ε)");
                        nextStat.setText("Next Statement : δ (" + t + ", ε)");
                    }
                    result = getResult(deltaNo);

                }
                
                if (result) {
                    AcceptRejectLbl.setText("'" + t + "' is final state,   ACCEPT!");
                } else {
                    if (t == null) {
                        AcceptRejectLbl.setText("it is not a state,    REJECT!");
                    } else {
                        AcceptRejectLbl.setText("'" + t + "' is not final state,    REJECT!");

                    }
                }
                 finish = true;

            } else if (nextCounter != inputText.getText().length()) {
                if (t != null) {
                    s = t;
                    //System.out.println(nextCounter + " - " + inputText.getText().length());
                    lightTheButton(s, inputText.getText().charAt(nextCounter));
                    nextStat.setText("Next Statement : δ (" + s + ", " + inputText.getText().charAt(nextCounter) + ") ");

                    panelMap.get(nextCounter + 1).setVisible(true);
                    labelMap.get(nextCounter + 1).setText("(" + s + ", " + inputText.getText().substring(nextCounter) + ")");
                    symbolMap.get(nextCounter + 1).setVisible(true);
                } else {
                    panelMap.get(nextCounter + 1).setVisible(true);
                    labelMap.get(nextCounter + 1).setText("( Ø , " + inputText.getText().substring(nextCounter) + ")");
                    symbolMap.get(nextCounter + 1).setVisible(true);

                    AcceptRejectLbl.setText("it is not a state,    REJECT!");
                    finish = true;

                }
            }
            nextCounter++;

        }
    }//GEN-LAST:event_nextButonActionPerformed

    private void inputTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextKeyReleased
        String pattern = inputText.getText();
        if (pattern.matches("[0-1]{1,10}")) {

            inputText.setBackground(Color.GREEN);

        } else {
            jLabel6.setText("* Your input should be up to 10 ");
            inputText.setBackground(Color.WHITE);

        }

    }//GEN-LAST:event_inputTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFA_Sampling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFA_Sampling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFA_Sampling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFA_Sampling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFA_Sampling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcceptRejectLbl;
    private javax.swing.JLabel Arrowa;
    private javax.swing.JLabel Arrowd;
    private javax.swing.JButton ChooseButton;
    private javax.swing.JPanel f1;
    private javax.swing.JPanel f10;
    private javax.swing.JPanel f11;
    private javax.swing.JPanel f2;
    private javax.swing.JPanel f3;
    private javax.swing.JPanel f4;
    private javax.swing.JPanel f5;
    private javax.swing.JPanel f6;
    private javax.swing.JPanel f7;
    private javax.swing.JPanel f8;
    private javax.swing.JPanel f9;
    private javax.swing.JLabel field1;
    private javax.swing.JLabel field10;
    private javax.swing.JLabel field11;
    private javax.swing.JLabel field2;
    private javax.swing.JLabel field3;
    private javax.swing.JLabel field4;
    private javax.swing.JLabel field5;
    private javax.swing.JLabel field6;
    private javax.swing.JLabel field7;
    private javax.swing.JLabel field8;
    private javax.swing.JLabel field9;
    private javax.swing.JList<String> grammerList;
    private javax.swing.JTextField grammerText;
    private javax.swing.JButton input0;
    private javax.swing.JButton input1;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton newState1;
    private javax.swing.JButton newState2;
    private javax.swing.JButton newState3;
    private javax.swing.JButton newState4;
    private javax.swing.JButton newState5;
    private javax.swing.JButton newState6;
    private javax.swing.JButton newState7;
    private javax.swing.JButton newState8;
    private javax.swing.JButton nextButon;
    private javax.swing.JLabel nextStat;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stat1;
    private javax.swing.JButton stat2;
    private javax.swing.JButton stat3;
    private javax.swing.JButton stat4;
    private javax.swing.JLabel symbol1;
    private javax.swing.JLabel symbol10;
    private javax.swing.JLabel symbol2;
    private javax.swing.JLabel symbol3;
    private javax.swing.JLabel symbol4;
    private javax.swing.JLabel symbol5;
    private javax.swing.JLabel symbol6;
    private javax.swing.JLabel symbol7;
    private javax.swing.JLabel symbol8;
    private javax.swing.JLabel symbol9;
    private javax.swing.JPanel transitionDiagramPanel;
    private javax.swing.JPanel transitionMatrix;
    // End of variables declaration//GEN-END:variables

}
